Updated maven.yml.

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -5,10 +5,41 @@ on:
   pull_request:
     branches: [ master ]
 jobs:
+  tests:
+    name: Unit tests
+    #Run on Ubuntu using the latest version
+    runs-on: ubuntu-latest
+    #Job's steps
+    steps:
+      #Check-out your repository under $GITHUB_WORKSPACE, so your workflow can access it
+      - uses: actions/checkout@v1
+      #Set up JDK 1.8
+      - name: Set up JDK
+        uses: actions/setup-java@v1
+        with:
+          java-version: '1.8'
+      #Set up Maven cache
+      - name: Cache Maven packages
+        #This action allows caching dependencies and build outputs to improve workflow execution time.
+        uses: actions/cache@v1
+        with:
+          path: ~/.m2
+          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
+          restore-keys: ${{ runner.os }}-m2
+      #Run Tests
+      - name: Run Tests
+        run: mvn -B test
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: JEST Tests            # Name of the check run which will be created
+          path: target/surefire-reports/TEST-*.xml    # Path to test results
+          reporter: java-junit        # Format of test results
   #Build's job
   build:
-    # needs: tests
-    name: Build and Push
+    needs: tests
+    name: Build image and Push to Docker
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
@@ -26,8 +57,8 @@ jobs:
       - name: Build with Maven and Push to Docker Hub
         run: mvn package -DskipTests=true -Pprod jib:build
   deploy:
-    #needs: build
-    name: Pull and Deploy
+    needs: build
+    name: Pull from Docker and Deploy to AWS EC2
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
@@ -40,7 +71,7 @@ jobs:
         envs: HITHUB_SHA
         script: |
           sudo yum install docker -y
-          sudo systemctl start docker
+          sudo systemctl restart docker
           sudo systemctl enable docker
           sudo systemctl restart docker
           sudo docker pull learnwithparth/sample
